<?php
namespace frontend\controllers;

use app\models\BaseModel;
use app\models\Project;
use Yii;
use yii\web\Controller;
/**
 * Site controller
 */
abstract class BaseController extends Controller
{
    public function getTitle()
    {
        $titles = Yii::$app->params['titles'];
        $controller_id = $this->id;
        $action_id = $this->action->id;
        return isset($titles[$controller_id . '/' . $action_id]) ? $titles[$controller_id . '/' . $action_id] : 'Empty';
    }

    public function render($view, $params = [])
    {
        if ($this->action->id != 'index')
        {
            $controller_id = $this->id;
            $action_id = 'index';
            $titles = Yii::$app->params['titles'];
            $labelParent = isset($titles[$controller_id . '/' . $action_id]) ? $titles[$controller_id . '/' . $action_id] : 'Empty';
            $UrlParent = '/' . $controller_id . '/' . $action_id;
            $params['breadcrumbs'][] = ['label' => $labelParent, 'url' => [$UrlParent]];
        }
        $params['title'] =  $this->getTitle();
        $params['breadcrumbs'][] =  $params['title'];
        return parent::render($view, $params); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        //\Tools::debug($this);
        return $this->render('//main/index');
    }
}
